steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--tag"
      - "europe-west1-docker.pkg.dev/${PROJECT_ID}/doc-processor-repo/doc-assistant-optimized:latest"
      - "--build-arg"
      - "HF_TOKEN_BUILD_ARG=${_HF_TOKEN}"
      - "."
images:
  - "europe-west1-docker.pkg.dev/${PROJECT_ID}/doc-processor-repo/doc-assistant-optimized:latest"
